Fix unit_price_vat_exclude + order number
evoliz/plugin-woocommerce pull request #2
Opened 2022-09-20 10:05 UTC by Plamp

Fix unit_price_vat_exclude when the price are set in TTC instead of HT
Fix the order number to get the real order number instead of woocomerce ID

2022-09-20 16:36 UTC, evoliz approved these changes

2022-09-21 08:06 UTC, julien-libert requested changes

2022-09-21 08:06 UTC, julien-libert commented on Class/EvolizSaleOrder.php
> +                //                $order->update_meta_data('evoliz', esc_attr(htmlspecialchars((string) $saleOrder)));
Ah ouais ca me fait vriller ca quand le comment est en début de ligne ca te pete tout pour plier le code.

2022-09-21 08:06 UTC, julien-libert commented on Class/EvolizSaleOrder.php
> +        $matchingSaleOrders = $saleOrderRepository->list(['search' => (string) $wcOrder->get_order_number()]);
Ca pose pas des problemes de retro compatibilité avec ceux qui l'ont utilisé avant ?

2022-09-21 08:06 UTC, julien-libert commented on Class/EvolizSaleOrder.php
> +                if (get_option('woocommerce_prices_include_tax') === 'yes') {
Utilise $unit_vat_exclude

2022-09-21 08:09 UTC, julien-libert approved these changes
Nice work !

2022-09-21 08:09 UTC, merged